# Generated by Django 3.1.3 on 2020-11-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('charCode', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
            ],
        ),
    ]
