# Generated by Django 3.1.3 on 2020-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_third_party_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymodel',
            name='data',
        ),
        migrations.AddField(
            model_name='currencymodel',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymodel',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencymodel',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
